# Generated by Django 2.2.5 on 2019-11-03 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0008_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='nickname',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
