# Generated by Django 2.2.5 on 2019-11-04 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0011_likedislike'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='likedislike',
            options={'verbose_name': 'Лайк', 'verbose_name_plural': 'Лайки'},
        ),
        migrations.AddField(
            model_name='likedislike',
            name='like_type',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
